_common/package: !include "../common/package.yaml"

name:        mprelude
version:     0.2.1
category:    prelude
synopsis:    A minimalish prelude.
description: |
  Prelude extracted from observing NoImplicitPrelude using
  projects by https://github.com/mbj.

  Idea is to not design a prelude, but to observe one by
  deduplicating repeated imports cross a larger project space.
extra-doc-files: README.md

<<: *defaults

dependencies:
- base
- source-constraints
- text
- unliftio-core      >= 0.2

default-extensions:
- CPP
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell

tests:
  test:
    <<: *test
