_common/package: !include "../common/package.yaml"

name:     dbt
version:  0.2.1
synopsis: DBT - DataBase tool

<<: *defaults

dependencies:
- base
- bytestring
- cbt
- cli-utils
- containers           >= 0.6
- control-bool
- conversions
- crypton
- hasql                >= 1.4
- hasql-th
- hasql-transaction
- memory
- mio-core
- mio-log
- mprelude
- mtl                  >= 2.2
- network
- optparse-applicative >= 0.15
- pathtype             >= 0.8
- template-haskell
- text
- th-lift-instances    >= 0.1
- typed-process        >= 0.2
- unliftio             >= 0.2
- unliftio-core        >= 0.2

library:
  source-dirs: src

executables:
  dbt:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - dbt
    when:
    - condition: flag(development)
      then:
        buildable: true
      else:
        buildable: false

tests:
  test:
    <<: *test
    dependencies:
    - dbt
    - devtools
    - tasty
    - tasty-hunit
    - tasty-mgolden
