_common/package: !include "../common/package.yaml"

name:    aws-checkip
version: 0.0.2

<<: *defaults

dependencies:
- base
- bytestring
- data-textual
- exceptions
- http-client
- http-client-tls
- http-mclient
- http-types
- mio-core
- mprelude
- network-ip
- text
- unliftio

tests:
  test:
    <<: *test
    dependencies:
    - aws-checkip
    - devtools
    - mio-log
    - tasty
    - tasty-hunit
