name:        openapi
version:     0.0.0.1
synopsis:    Openapi3 Types
homepage:    https://github.com/mbj/openapi
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/openapi

dependencies:
- aeson                ^>= 1.4 && >= 1.4.7.0
- attoparsec           ^>= 0.13
- base                 ^>= 4.12
- bytestring           ^>= 0.10
- conduit              ^>= 1.3
- containers           ^>= 0.6
- exceptions           ^>= 0.10
- ghc                  ^>= 8.6
- http-types           ^>= 0.12
- mprelude             == 0.0.0.1
- pathtype             ^>= 0.8
- source-constraints   == 0.0.0.1
- text                 ^>= 1.2
- text-conversions     ^>= 0.3
- unordered-containers ^>= 0.2
- yaml                 ^>= 0.11

extra-source-files: []

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -fplugin=SourceConstraints
- -fplugin-opt=SourceConstraints:local:Gen

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict

library:
  source-dirs:
  - src
  exposed-modules:
  - OpenApi
  - OpenApi.Paths
  - OpenApi.Schema
  - OpenApi.Types
tests:
  tasty:
    main:          Main.hs
    source-dirs:   test
    other-modules: []
    dependencies:
    - devtools
    - openapi
    - tasty
    - tasty-hunit
    - unordered-containers
