name:       xray
synopsis:   Recording and submitting traces for Amazon XRay
homepage:   https://github.com/mbj/xray
maintainer: Markus Schirp mbj@schirp-dso.com
copyright:  Markus Schirp
license:    MIT
github:     mbj/xray
version:    0.0.1

dependencies:
- aeson                ^>= 1.4 || ^>= 1.5
- attoparsec           ^>= 0.13
- base                 ^>= 4.13 || ^>= 4.14
- binary               ^>= 0.8
- bytestring           ^>= 0.10
- conversions          ^>= 0.0.4
- hashable             ^>= 1.3
- http-types           ^>= 0.12
- mprelude             ^>= 0.2.0
- mrio-core            ^>= 0.0.1
- mtl                  ^>= 2.2
- network              ^>= 3.1 && >= 3.1.2
- pathtype             ^>= 0.8
- random               ^>= 1.1
- scientific           ^>= 0.3
- source-constraints   ^>= 0.0.2
- symbols              ^>= 0.3
- template-haskell     ^>= 2.15 || ^>= 2.16
- text                 ^>= 1.2
- time                 ^>= 1.9
- unliftio             ^>= 0.2
- unordered-containers ^>= 0.2

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-local-signatures
- -Wmissing-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- PolyKinds
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs: src

tests:
  test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools ^>= 0.1
    - tasty
    - tasty-hunit
    - xray
