name:        source-constraints
version:     0.0.0.1
synopsis:    Source constraints GHC plugin
homepage:    https://github.com/schirp-dso/source-constraints#readme
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2018 Markus Schirp
category:    CodeQuality
github:      schirp-dso/source-constraints

dependencies:
- attoparsec ^>= 0.13.2.2
- base       ^>= 4.12.0.0
- bytestring ^>= 0.10.8.2
- filepath   ^>= 1.4.2.1
- ghc        ^>= 8.6.5
- syb        ^>= 0.7.1
- text       ^>= 1.2.3.1

extra-source-files:
- test/LocalModuleExplicitImport.hs
- test/MissingDerivingStrategy.hs
- test/UnsortedIE.hs
- test/UnsortedIEThingWith.hs
- test/UnsortedImportStatement.hs
- test/UnsortedMultipleDeriving.hs

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction

default-extensions:
- DerivingStrategies
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict

library:
  source-dirs:
  - src
  exposed-modules:
  - SourceConstraints
  - SourceConstraints.LocalModule

tests:
  hspec:
    main:          Spec.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - ghc-paths          == 0.1.0.12
    - heredoc            == 0.2.0.0
    - hspec              == 2.7.1
    - source-constraints
  devtools:
    main:          test/Devtools.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
