name:        mprelude
version:     0.0.0.1
github:      mbj/mprelude
description: Please see the README on Github at <https://github.com/mbj/mprelude#readme>
license:     AllRightsReserved

dependencies:
- base               == 4.12.0.0
- source-constraints == 0.0.0.1
- text               == 1.2.3.1
- text-conversions   == 0.3.0

library:
  source-dirs: src

default-extensions:
- CPP
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

tests:
  hlint:
    main:          HLint.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hlint == 2.1.11
