name:        devtools
version:     0.0.2
github:      mbj/devtools-hs
synopsis:    Haskell development tool agregate
category:    Testing
author:      Markus Schirp <mbj@schirp-dso.com>
license:     BSD3
description: |
  An attempt to group development that would typically run on CI / local
  into one tasty interface.

dependencies:
- Diff               > 0.3 && < 0.5
- base               > 4.12 && < 4.14
- bytestring         ^>= 0.10
- cmdargs            ^>= 0.10.20
- filepath           ^>= 1.4
- hlint              > 3.1 && < 4
- mprelude           ^>= 0.1.0
- source-constraints ^>= 0.0.1
- tasty              ^>= 1.3.1
- tasty-mgolden      ^>= 0.0.1
- text               ^>= 1.2
- typed-process      ^>= 0.2

flags:
  development:
    description: Run GHC with development flags
    default: false
    manual: true

library:
  source-dirs: src

extra-doc-files:
- README.md

default-extensions:
- DerivingStrategies
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- StrictData

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

when:
  - condition: flag(development)
    then:
      ghc-options: -Werror
    else:
      ghc-options: -Wwarn

executables:
  devtools: &devtools
    main:        app/Main.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools

tests:
  devtools-test: *devtools
