name:        source-constraints
version:     0.0.1
synopsis:    Source constraints GHC plugin
homepage:    https://github.com/mbj/source-constraints#readme
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2018 Markus Schirp
category:    CodeQuality
github:      mbj/source-constraints
license:     BSD3

dependencies:
- attoparsec ^>= 0.13
- base       ^>= 4.13
- bytestring ^>= 0.10
- filepath   ^>= 1.4
- ghc        ^>= 8.8
- syb        ^>= 0.7
- text       ^>= 1.2

extra-doc-files:
- README.md

flags:
  development:
    description: Run GHC with development flags
    default: false
    manual: true

extra-source-files:
- test/LocalModuleExplicitImport.hs
- test/MissingDerivingStrategy.hs
- test/UnsortedIE.hs
- test/UnsortedIEThingWith.hs
- test/UnsortedImportStatement.hs
- test/UnsortedMultipleDeriving.hs

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction

when:
  - condition: flag(development)
    then:
      ghc-options: -Werror
    else:
      ghc-options: -Wwarn

default-extensions:
- DerivingStrategies
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict

library:
  source-dirs:
  - src
  exposed-modules:
  - SourceConstraints
  - SourceConstraints.LocalModule

tests:
  hspec:
    main:          Spec.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - ghc-paths          ^>= 0.1
    - heredoc            ^>= 0.2
    - hspec              ^>= 2.7
    - source-constraints
