name:        pgt
version:     0.0.1
github:      mbj/pgt
license:     AllRightsReserved

extra-source-files:
- spec/failure.expected
- spec/failure.sql
- spec/success.expected
- spec/success.sql

dependencies:
- Diff                 == 0.3.4
- base                 == 4.12.0.0
- bytestring           == 0.10.8.2
- directory            == 1.3.3.0
- filepath             == 1.4.2.1
- hspec                == 2.7.1
- hspec-core           == 2.7.1
- mprelude             == 0.0.0.1
- optparse-applicative == 0.14.3.0
- ordered-containers   == 0.2.1
- source-constraints   == 0.0.0.1
- text                 == 1.2.3.1
- text-conversions     == 0.3.0
- typed-process        == 0.2.6.0
- unix                 == 2.7.2.2
- unliftio             == 0.2.12
- unliftio-core        == 0.1.2.0

library:
  source-dirs: src

default-extensions:
- CPP
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin-opt=SourceConstraints:local:Pgt
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

executables:
  pgt:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - pgt

tests:
  devtools:
    main:          test/Devtools.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
  hspec:
    main:        Spec.hs
    source-dirs: spec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hspec == 2.7.1
    - pgt
