name:        tasty-mgolden
version:     0.0.1
github:      mbj/tasty-mgolden
synopsis:    Golden testing provider for tasty with muti-line diff output
license:     BSD3
author:      Markus Schirp <mbj@schirp-dso.com>
category:    Testing
tested-with: GHC ==8.6.5 || ==8.8.4 || ==8.10.2
description: |
  Please visit the README at <https://github.com/mbj/tasty-mgolden#readme>
  for usage information.

dependencies:
- Diff        == 0.3.4 || ^>= 0.4
- base        >= 4.12  && <= 4.15
- filepath    ^>= 1.4.2
- tasty       ^>= 1.3.1
- text        ^>= 1.2

extra-doc-files:
- README.md

flags:
  development:
    description: Run GHC with development flags
    default: false
    manual: true

library:
  source-dirs: src

default-extensions:
- DerivingStrategies
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- StrictData

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -funbox-strict-fields

when:
  - condition: flag(development)
    then:
      ghc-options: -Werror
    else:
      ghc-options: -Wwarn

tests:
  hlint:
    main:          HLint.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hlint

  golden:
    main:          test/Test.hs
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - tasty-expected-failure
    - tasty-hunit
    - tasty-mgolden
    - typed-process

executables:
  tasty-mgolden-example:
    main:          example/Test.hs
    other-modules: []
    default-extensions:
    - ImplicitPrelude
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-implicit-prelude
    dependencies:
    - tasty-expected-failure
    - tasty-hunit
    - tasty-mgolden
