name:        pgt
version:     0.0.1
github:      mbj/pgt
license:     AllRightsReserved

extra-source-files:
- examples/failure.expected
- examples/failure.sql
- examples/success.expected
- examples/success.sql

dependencies:
- Diff                 ^>= 0.3
- base                 ^>= 4.12
- bytestring           ^>= 0.10
- containers           ^>= 0.6
- directory            ^>= 1.3
- filepath             ^>= 1.4
- mprelude             == 0.0.0.1
- optparse-applicative ^>= 0.14
- ordered-containers   ^>= 0.2
- pathtype             ^>= 0.8.1
- source-constraints   == 0.0.0.1
- tasty                ^>= 1.2
- tasty-mgolden        == 0.0.0.1
- text                 ^>= 1.2
- text-conversions     ^>= 0.3
- typed-process        ^>= 0.2
- unix                 ^>= 2.7
- unliftio             ^>= 0.2
- unliftio-core        ^>= 0.1

library:
  source-dirs: src

default-extensions:
- CPP
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin-opt=SourceConstraints:local:Pgt
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

executables:
  pgt:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - pgt

tests:
  devtools:
    main:          test/Devtools.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
