name:        openapi
version:     0.0.0.1
synopsis:    Openapi3 Types
homepage:    https://github.com/mbj/openapi
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/openapi

dependencies:
- aeson                == 1.4.5.0
- attoparsec           == 0.13.2.3
- base                 == 4.12.0.0
- bytestring           == 0.10.8.2
- conduit              == 1.3.1.1
- containers           == 0.6.0.1
- exceptions           == 0.10.3
- filepath             == 1.4.2.1
- ghc                  == 8.6.5
- http-types           == 0.12.3
- mprelude             == 0.0.0.1
- source-constraints   == 0.0.0.1
- text                 == 1.2.3.1
- text-conversions     == 0.3.0
- unordered-containers == 0.2.10.0

extra-source-files: []

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -fplugin=SourceConstraints
- -fplugin-opt=SourceConstraints:local:Gen

default-extensions:
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict

library:
  source-dirs:
  - src
  exposed-modules:
  - OpenApi
  - OpenApi.Paths
  - OpenApi.Schema
  - OpenApi.Types
tests:
  hlint:
    main:          HLint.hs
    source-dirs:   test
    other-modules: []
    dependencies:
    - hlint == 2.1.26
  tasty:
    main:          Main.hs
    source-dirs:   test
    other-modules: []
    dependencies:
    - openapi
    - tasty       == 1.2.3
    - tasty-hunit == 0.10.0.2
    - unordered-containers
