resolver: lts-14.7
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: a2219661a1853552edd3a50b30c243ca5c634f6e
- git: https://github.com/mbj/tasty
  commit: 4f97799635560e5ce60d933f4a0feaa607ad10df
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: a2e538036e16aa6b002de7bf39392fa0a2d7c370
