resolver: lts-14.11
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: fdf83fb9875b7ea2b0d0801cea0f269daea5ed4b
- git: https://github.com/mbj/mprelude
  commit: 4b320792e3bbf8a6e2660d29466abfe3db865c7f
- git: https://github.com/mbj/source-constraints
  commit: d7678cfa96c98cf411cee5bf8aff9546fa2d31c1
- git: https://github.com/mbj/tasty
  commit: 4f97799635560e5ce60d933f4a0feaa607ad10df
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: a2e538036e16aa6b002de7bf39392fa0a2d7c370
