resolver: lts-15.11
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: db02e6f80f27cb672b919e5ab078ebdfad996f3b
- git: https://github.com/mbj/source-constraints
  commit: c57de5486d5ac383ef7013485e4d2c35cc8bd2f4
- git: https://github.com/mbj/tasty
  commit: 6b884dc97902feaf6e81ad46f3cc905eb122e5d6
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: 68e10ddcd37aa872c9d0cd57a1665d09ac4ddbc0
