build:
  haddock: false
extra-deps:
- ordered-containers-0.2.1
- git: https://github.com/mbj/mprelude
  commit: 15726838548d859c19d2b7135e60b7acc3d3ae1b
- git: https://github.com/schirp-dso/source-constraints
  commit: 3eea6c0c3c4c66c39e1b68a5a27e74554395699d
packages:
- .
resolver: lts-14.7
