build:
  haddock: false
resolver: lts-14.27
extra-deps:
- git: https://github.com/mbj/cbt
  commit: 990a2f3274d03b3626607adfb3528f315c498f44
- git: https://github.com/mbj/devtools-hs
  commit: 4a05908e59690ed852fde484eb0b2a57f8fb1ae6
- git: https://github.com/mbj/mprelude
  commit: 451e3c2bed257c42e45dfb00d66376285cfaa56f
- git: https://github.com/mbj/source-constraints
  commit: 75ba67ba7a8853db3c2ca22c5db10dbe883e1dae
- git: https://github.com/mbj/tasty
  commit: 6b884dc97902feaf6e81ad46f3cc905eb122e5d6
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: 888ae7b63716f7e4d9b6703cb5dae840cd3a328b
