build:
  haddock: false
resolver: lts-13.28
extra-deps:
- stratosphere-0.38.0
- git: https://github.com/schirp-dso/source-constraints
  commit: 008e5ce4a6660e2f35924b019272803206e01cb2
- git: https://github.com/mbj/mprelude
  commit: 792cda1dc3e51253264aa76eb984b932d428c683
- git: https://github.com/mbj/amazonka
  commit: 33aa6b71309793829b534fb29f6532d71c32b106
  subdirs:
  - amazonka-cloudformation
