resolver: lts-13.28
extra-deps:
- commit: c64f467f455f0632eeeb1efa81fa9739985136ad
  git: https://github.com/schirp-dso/source-constraints
- commit: 792cda1dc3e51253264aa76eb984b932d428c683
  git: https://github.com/mbj/mprelude
packages:
- .
