resolver: lts-14.27
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: 5b9e3d84b3cce4afbc701dd34d4f8ced51dd0aa5
- git: https://github.com/mbj/tasty
  commit: ff484ef812277ad27a9c9449b4597be30c845b13
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: a2e538036e16aa6b002de7bf39392fa0a2d7c370
