resolver: lts-14.27
build:
  haddock: false
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: 4a05908e59690ed852fde484eb0b2a57f8fb1ae6
- git: https://github.com/mbj/mprelude
  commit: 451e3c2bed257c42e45dfb00d66376285cfaa56f
- git: https://github.com/mbj/source-constraints
  commit: 3eea6c0c3c4c66c39e1b68a5a27e74554395699d
- git: https://github.com/mbj/tasty
  commit: 6b884dc97902feaf6e81ad46f3cc905eb122e5d6
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: 42d35574b29b52c8357676375aa4d91223d3e9bc
- git: https://github.com/mbj/dbt
  commit: be656186088cff0f4742aba3ab6116ae8a1aa49a
