resolver: lts-14.11
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: fdf83fb9875b7ea2b0d0801cea0f269daea5ed4b
- git: https://github.com/mbj/tasty
  commit: ff484ef812277ad27a9c9449b4597be30c845b13
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: a2e538036e16aa6b002de7bf39392fa0a2d7c370
