resolver: lts-14.27
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: 5b9e3d84b3cce4afbc701dd34d4f8ced51dd0aa5
- git: https://github.com/mbj/tasty
  commit: 049bacbabd35b5a91ffb0beb115026e6bd5ab127
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: f91ac9424352d4844b0acd237323acf91943ad82
