resolver: lts-15.11
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: db02e6f80f27cb672b919e5ab078ebdfad996f3b
- git: https://github.com/mbj/tasty
  commit: 6b884dc97902feaf6e81ad46f3cc905eb122e5d6
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: 3bdcddb38d1d2005a205fb4c1d35e88bc3f3f432
