resolver: lts-14.11
extra-deps:
- git: https://github.com/mbj/devtools-hs
  commit: 2dabd175a4ea86dee89f79f56ffaea66db3f3a62
- git: https://github.com/mbj/mprelude
  commit: 1fefadb9172a5b08b98180aab2bd669724c74287
- git: https://github.com/mbj/source-constraints
  commit: 75ba67ba7a8853db3c2ca22c5db10dbe883e1dae
- git: https://github.com/mbj/tasty
  commit: 4f97799635560e5ce60d933f4a0feaa607ad10df
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: a2e538036e16aa6b002de7bf39392fa0a2d7c370
