_common/package: !include "../common/package.yaml"

name:        dbt-postgresql-connection
version:     0.1.0
synopsis:    DBT Postgresql database connection
github:      mbj/dbt

<<: *defaults

dependencies:
- base
- bytestring
- containers
- conversions
- hasql              >= 1.4
- mprelude
- mio-core
- mtl                >= 2.2
- source-constraints
- text
- unliftio           >= 0.2

tests:
  test:
    <<: *test
    dependencies:
    - dbt-postgresql-connection
    - devtools
