_common/package: !include "../common/package.yaml"

name:        openapi
version:     0.0.2
synopsis:    Openapi3 Types
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com

<<: *defaults

dependencies:
- aeson                >= 1.5
- attoparsec           >= 0.13
- base
- bytestring
- conduit              >= 1.3
- containers           >= 0.6
- conversions
- exceptions           >= 0.10
- http-types           >= 0.12
- mprelude
- mtl
- pathtype             >= 0.8
- scientific           >= 0.3
- source-constraints   >= 0.0.1
- text
- unordered-containers >= 0.2
- yaml                 >= 0.11

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict
- TupleSections
- TypeApplications

tests:
  tasty:
    <<: *test
    dependencies:
    - devtools
    - openapi
    - tasty
    - tasty-hunit
    - unordered-containers
