_common/package: !include "../common/package.yaml"

name:        db-migrations
description: Please see the README on GitHub at <https://github.com/mbj/db-migrations#readme>
version:     0.0.1
author:      Markus Schirp

<<: *defaults

extra-doc-files:
- README.md
- ChangeLog.md

dependencies:
- base
- bytestring                ^>= 0.10
- containers                ^>= 0.6
- control-bool              ^>= 0.2
- conversions               ^>= 0.0.3
- cryptonite                >= 0.26 && < 1
- dbt-postgresql-connection ^>= 0.1.0
- hasql                     ^>= 1.4
- hasql-th                  ^>= 0.4
- hasql-transaction         ^>= 1.0
- memory                    ^>= 0.15 || ^>= 0.16
- mprelude                  ^>= 0.2
- mrio-core                 ^>= 0.0.1
- mtl                       ^>= 2.2
- network                   ^>= 3.1
- optparse-applicative      ^>= 0.15 || ^>= 0.16
- pathtype                  ^>= 0.8
- source-constraints        ^>= 0.0.1
- template-haskell
- text                      ^>= 1.2
- th-lift-instances         ^>= 0.1
- typed-process             ^>= 0.2
- unliftio                  ^>= 0.2

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications

tests:
  test:
    <<: *test
    dependencies:
    - devtools ^>= 0.1.0
