_common/package: !include "../common/package.yaml"

name:        db-migrations
description: Please see the README on GitHub at <https://github.com/mbj/db-migrations#readme>
version:     0.0.2
author:      Markus Schirp

<<: *defaults

extra-doc-files:
- README.md
- ChangeLog.md

dependencies:
- base
- bytestring
- containers
- control-bool         >= 0.2
- conversions          >= 0.0.3
- crypton
- dbt
- hasql                >= 1.4
- hasql-th             >= 0.4
- hasql-transaction    >= 1.0
- memory               >= 0.15
- mio-core             >= 0.0.1
- mprelude             >= 0.2
- mtl
- network
- optparse-applicative >= 0.15
- pathtype             >= 0.8
- source-constraints
- template-haskell
- text
- th-lift-instances    >= 0.1
- typed-process        >= 0.2
- unliftio             >= 0.2

tests:
  test:
    <<: *test
