name:        db-migrations
description: Please see the README on GitHub at <https://github.com/mbj/db-migrations#readme>
version:     0.0.1
github:      mbj/db-migrations
license:     AllRightsReserved
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2020 Markus Schirp

extra-doc-files:
- README.md
- ChangeLog.md

dependencies:
- base
- bytestring                ^>= 0.10
- containers                ^>= 0.6
- control-bool              ^>= 0.2
- conversions               ^>= 0.0.3
- cryptonite                >= 0.26 && < 1
- dbt-postgresql-connection ^>= 0.1.0
- hasql                     ^>= 1.4
- hasql-th                  ^>= 0.4
- hasql-transaction         ^>= 1.0
- memory                    ^>= 0.15 || ^>= 0.16
- mprelude                  ^>= 0.2
- mrio-core                 ^>= 0.0.1
- mtl                       ^>= 2.2
- network                   ^>= 3.1
- optparse-applicative      ^>= 0.15 || ^>= 0.16
- pathtype                  ^>= 0.8
- source-constraints        ^>= 0.0.1
- template-haskell
- text                      ^>= 1.2
- th-lift-instances         ^>= 0.1
- typed-process             ^>= 0.2
- unliftio                  ^>= 0.2

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications

library:
  source-dirs: src

tests:
  devtools:
    main:         test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools ^>= 0.1.0
