_common/package: !include "../common/package.yaml"

name:        lht
version:     0.0.1
synopsis:    AWS Lambda haskell tool

<<: *defaults

dependencies:
- base
- bytestring         ^>= 0.10
- cbt                ^>= 0.1.0
- conversions        ^>= 0.0.3
- directory          ^>= 1.3
- elf                ^>= 0.30 || ^>= 0.31
- exceptions         ^>= 0.10
- http-types         ^>= 0.12
- mprelude           ^>= 0.2
- mrio-core          ^>= 0.0.1
- pathtype           ^>= 0.8
- source-constraints ^>= 0.0.1
- tar                ^>= 0.5
- template-haskell
- text               ^>= 1.2
- text-conversions   ^>= 0.3
- th-lift-instances  ^>= 0.1
- time               ^>= 1.9
- typed-process      ^>= 0.2
- unix               ^>= 2.7
- unliftio           ^>= 0.2
- unliftio-core      ^>= 0.2
- uuid               ^>= 1.3
- zip-archive        ^>= 0.4

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell
- TypeApplications

library:
  source-dirs:
  - src
  exposed-modules:
  - LHT.Build
  - LHT.Zip

tests:
  test:
    <<: *test
    dependencies:
    - devtools
    - lht
    - tasty         ^>= 1.3
    - tasty-hunit   ^>= 0.10
