_common/package: !include "../common/package.yaml"

name:        lht
version:     0.0.1
synopsis:    AWS Lambda haskell tool

<<: *defaults

dependencies:
- base
- bytestring
- cbt
- conversions
- directory
- elf                >= 0.30
- exceptions
- http-types         >= 0.12
- mprelude           >= 0.2
- mrio-core
- pathtype           >= 0.8
- source-constraints
- tar                >= 0.5
- template-haskell
- text
- th-lift-instances  >= 0.1
- time
- typed-process      >= 0.2
- unix
- unliftio           >= 0.2
- unliftio-core      >= 0.2
- uuid               >= 1.3
- zip-archive        >= 0.4

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell
- TypeApplications

library:
  source-dirs:
  - src
  exposed-modules:
  - LHT.Build
  - LHT.Zip

tests:
  test:
    <<: *test
    dependencies:
    - devtools
    - lht
    - tasty
    - tasty-hunit
