_common/package: !include "../common/package.yaml"

name:        lht
version:     0.0.4
synopsis:    AWS Lambda haskell tool

<<: *defaults

dependencies:
- base
- bytestring
- cbt
- conversions
- directory
- elf                >= 0.30
- exceptions
- ghc-boot
- http-types         >= 0.12
- mio-core
- mprelude           >= 0.2
- pathtype           >= 0.8
- tar                >= 0.5
- template-haskell
- text
- th-lift-instances  >= 0.1
- time
- typed-process      >= 0.2
- unix
- unliftio           >= 0.2
- unliftio-core      >= 0.2
- uuid               >= 1.3
- zip-archive        >= 0.4

library:
  source-dirs:
  - src
  exposed-modules:
  - LHT.Build
  - LHT.GHC
  - LHT.Zip

tests:
  test:
    <<: *test
    dependencies:
    - devtools
    - lht
    - tasty
    - tasty-hunit
