_common/package: !include "../common/package.yaml"

name:       mrio-amazonka
synopsis:   Amazonka integration for mrio
maintainer: Markus Schirp <mbj@schirp-dso.com>, Allan Lukwago <epicallan.al@gmail.com>
version:    0.0.1

<<: *defaults

dependencies:
- amazonka           >= 1.6.1 && < 2
- base
- conduit            >= 1.3
- mrio-core
- mtl
- resourcet          >= 1.2.4
- source-constraints
- unliftio-core      >= 0.2

tests:
  test:
    <<: *test
    dependencies:
    - devtools
    - mrio-core
    - mrio-amazonka
