_common/package: !include "../common/package.yaml"

maintainer: Markus Schirp mbj@schirp-dso.com, Allan Lukwago <epicallan.al@gmail.com>
name:       bounded
synopsis:   User definable Integral and Text bounded types
version:    0.0.1

<<: *defaults

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ExistentialQuantification
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- PolyKinds
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

library:
  source-dirs: src
  dependencies:
  - base
  - aeson              >= 1.3
  - conversions        >= 0.0.2
  - mtl
  - scientific
  - symbols
  - text               >= 1.2

tests:
  test:
    <<: *test
    dependencies:
    - aeson              >= 1.3
    - base
    - bounded
    - should-not-typecheck
    - source-constraints ^>= 0.0.2
    - tasty
    - tasty-hunit
    - type-spec
    - devtools >= 0.1.0

  readme:
    main: README.lhs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -pgmL markdown-unlit
    - -Wno-unused-top-binds
    dependencies:
    - base
    - bounded
    - markdown-unlit
    - text
