github:     mbj/mhs
homepage:   https://github.com/mbj/mhs#readme
license:    MIT
maintainer: Markus Schirp mbj@schirp-dso.com, Allan Lukwago <epicallan.al@gmail.com>
name:       bounded
synopsis:   User definable Integral and Text bounded types
version:    0.0.1

flags:
  development:
    description: Run GHC with development flags
    default: false
    manual: true

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-local-signatures
- -Wmissing-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ExistentialQuantification
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- PolyKinds
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

library:
  source-dirs: src
  dependencies:
  - base
  - aeson              >= 1.3
  - conversions        >= 0.0.2
  - mtl
  - scientific
  - symbols
  - text               >= 1.2

when:
  - condition: flag(development)
    then:
      ghc-options:
      - -Werror
      - -fplugin=SourceConstraints
      dependencies:
      - source-constraints ^>= 0.0.2
    else:
      ghc-options: -Wwarn

tests:
  test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - aeson              >= 1.3
    - base
    - bounded
    - should-not-typecheck
    - source-constraints ^>= 0.0.2
    - tasty
    - tasty-hunit
    - type-spec
    - devtools >= 0.1.0

  readme:
    main: README.lhs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -pgmL markdown-unlit
    - -Wno-unused-top-binds
    dependencies:
    - base
    - bounded
    - markdown-unlit
    - text
