_common/package: !include "../common/package.yaml"

maintainer: Markus Schirp mbj@schirp-dso.com, Allan Lukwago <epicallan.al@gmail.com>
name:       bounded
synopsis:   User definable Integral and Text bounded types
version:    0.0.4

<<: *defaults

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ExistentialQuantification
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- PolyKinds
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

dependencies:
- aeson       >= 1.3
- base
- conversions
- mtl
- scientific
- symbols
- template-haskell
- text

library:
  source-dirs: src

tests:
  test:
    <<: *test
    dependencies:
    - bounded
    - should-not-typecheck
    - source-constraints
    - tasty
    - tasty-hunit
    - type-spec
    - devtools

  readme:
    main: README.lhs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -pgmL markdown-unlit
    - -Wno-unused-top-binds
    dependencies:
    - base
    - bounded
    - markdown-unlit
    - text
