_common/package: !include "../common/package.yaml"

name:        devtools
version:     0.1.0
synopsis:    Haskell development tool agregate
category:    Testing
license:     BSD3
description: |
  An attempt to group development that would typically run on CI / local
  into one tasty interface.

<<: *defaults

dependencies:
- Diff               > 0.3 && < 0.5
- base
- bytestring         ^>= 0.10
- cmdargs            ^>= 0.10.20
- filepath           ^>= 1.4
- hlint              > 3.1 && < 4
- mprelude           ^>= 0.2.0
- tasty              ^>= 1.3.1
- tasty-mgolden      ^>= 0.0.1
- text               ^>= 1.2
- typed-process      ^>= 0.2

extra-doc-files:
- README.md

default-extensions:
- DerivingStrategies
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- StrictData

tests:
  test:
    <<: *test
