_common/package: !include "../common/package.yaml"

name:       mrio-log
synopsis:   Minimal mrio based logger
homepage:   https://github.com/mbj/mhs#readme
github:     mbj/mhs
version:    0.0.1

<<: *defaults

dependencies:
- base
- bytestring
- conversions
- mprelude
- mrio-core
- mtl
- text
- time

default-extensions:
- DataKinds
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- PolyKinds
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- UndecidableInstances

tests:
  test:
    <<: *test
    dependencies:
    - devtools
    - mrio-core
    - mrio-log
    - tasty
    - tasty-hunit
