_common/package: !include "../common/package.yaml"

name:       mrio-log
synopsis:   Minimal mrio based logger
homepage:   https://github.com/mbj/mhs#readme
github:     mbj/mhs
version:    0.0.3

<<: *defaults

dependencies:
- base
- bytestring
- conversions
- mprelude
- mrio-core
- mtl
- text
- time

tests:
  test:
    <<: *test
    dependencies:
    - devtools
    - mrio-core
    - mrio-log
    - tasty
    - tasty-hunit
