AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test for the Haskell Runtime
Resources:
  helloworld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: NOT_USED
      Runtime: provided
      CodeUri: ../../.stack-work/docker/_home/.local/bin/
      Description: Test for the Haskell Runtime.
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
              Resource: 'arn:aws:s3:::my-bucket/*'
