_common/package: !include "../common/package.yaml"

name:                http-mclient
synopsis:            Minimal http-client
description:         Minimal http-client built on top of http-client library
version:             0.0.1
author:              gamsnjaga@gmail.com, epicallan.al@gmail.com
maintainer:          gamsnjaga@gmail.com, epicallan.al@gmail.com, mbj@schirp-dso.com
category:            Web
extra-source-files:
- README.md

<<: *defaults

dependencies:
- base
- aeson
- bounded
- bytestring
- case-insensitive
- conversions
- http-client
- http-media
- http-types
- exceptions
- mtl
- mprelude
- text

default-extensions:
- AllowAmbiguousTypes
- OverloadedStrings
- OverloadedLists
- DeriveFunctor
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DataKinds
- KindSignatures
- DuplicateRecordFields
- ConstraintKinds
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- MonoLocalBinds
- MultiWayIf
- MultiParamTypeClasses
- RecordWildCards
- ScopedTypeVariables
- TypeApplications

tests:
  test:
    <<: *test
