_common/package: !include "../common/package.yaml"

name:        dbt-postgresql-connection
version:     0.1.0
synopsis:    DBT Postgresql database connection
github:      mbj/dbt

<<: *defaults

dependencies:
- base
- bytestring         ^>= 0.10
- containers         ^>= 0.6
- conversions        ^>= 0.0.3
- hasql              ^>= 1.4
- mprelude           ^>= 0.2.0
- mrio-core          ^>= 0.0.1
- mtl                ^>= 2.2
- source-constraints ^>= 0.0.2
- text               ^>= 1.2
- unliftio           ^>= 0.2

tests:
  test:
    <<: *test
    dependencies:
    - dbt-postgresql-connection
    - devtools
