name:        dbt-postgresql-connection
version:     0.1.0
synopsis:    DBT Postgresql database connection
homepage:    https://github.com/mbj/dbt
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/dbt
license:     BSD3

dependencies:
- base               ^>= 4.12 || ^>= 4.13 || ^>= 4.14
- bytestring         ^>= 0.10
- containers         ^>= 0.6
- conversions        ^>= 0.0.3
- hasql              ^>= 1.4
- mprelude           ^>= 0.2.0
- mrio-core          ^>= 0.0.1
- mtl                ^>= 2.2
- source-constraints ^>= 0.0.2
- text               ^>= 1.2
- unliftio           ^>= 0.2

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell
- TypeApplications

library:
  source-dirs: src

tests:
  test:
    main: test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - dbt-postgresql-connection
    - devtools ^>= 0.1.0
