- &defaults
  author:     Markus Schirp
  copyright:  2023 Markus Schirp
  github:     mbj/mhs
  homepage:   https://github.com/mbj/mhs#readme
  license:    BSD3
  maintainer: mbj@schirp-dso.com

  tested-with:
  - GHC == 9.4
  - GHC == 9.6

  when:
  - condition: flag(development)
    then:
      ghc-options: -Werror
    else:
      ghc-options: -Wwarn

  # GHC 9.6 currently doesn't play nice with plugins when stack
  # https://github.com/commercialhaskell/stack/issues/6251
  - condition: impl(ghc < 9.5)
    ghc-options: -fplugin=SourceConstraints
    dependencies: source-constraints

  ghc-options:
  - -Wall
  - -Wcompat
  - -Werror
  - -Widentities
  - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wmissing-local-signatures
  - -Wmissing-signatures
  - -Wmonomorphism-restriction
  - -Wno-ambiguous-fields
  - -Wredundant-constraints
  - -fhide-source-paths
  - -funbox-strict-fields
  - -optP-Wno-nonportable-include-path

  default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoFieldSelectors
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedLists
  - OverloadedRecordDot
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns

  library:
    source-dirs: src

  flags:
    development: &development_flag
      description: Run GHC with development flags
      default: false
      manual: true

- &test
  main: Test.hs
  source-dirs: test
  ghc-options:
  - -rtsopts
  - -threaded
  - -with-rtsopts=-N
  dependencies:
  - devtools
