_common/package: !include "../common/package.yaml"

name:        dbt-postgresql-container
version:     0.2.0
synopsis:    DBT Postgresql container tool

<<: *defaults

dependencies:
- base
- bytestring
- cbt
- containers                >= 0.6
- conversions
- dbt-postgresql-connection
- hasql                     >= 1.4
- mprelude
- mrio-log
- mrio-core
- mtl                       >= 2.2
- network
- optparse-applicative      >= 0.15
- pathtype                  >= 0.8
- source-constraints
- template-haskell
- text
- th-lift-instances         >= 0.1
- typed-process             >= 0.2
- unliftio                  >= 0.2
- unliftio-core             >= 0.2

library:
  source-dirs: src
  exposed-modules:
  - DBT.Postgresql.Container
  - DBT.Postgresql.Container.CLI

executables:
  dbt:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - dbt-postgresql-container

tests:
  test:
    <<: *test
    dependencies:
    - dbt-postgresql-connection
    - dbt-postgresql-container
    - devtools
    - tasty
    - tasty-mgolden
