_common/package: !include "../common/package.yaml"

maintainer: Markus Schirp mbj@schirp-ds.com, Allan Lukwago <epicallan.al@gmail.com>
name:       conversions
synopsis:   Injective explicit total and partial conversions
version:    0.0.6

<<: *defaults

dependencies:
- base
- bytestring
- exceptions
- mtl
- scientific
- template-haskell
- text

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- ExistentialQuantification
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

tests:
  test:
    <<: *test
    dependencies:
    - conversions
    - devtools
