_common/package: !include "../common/package.yaml"

name:        cbt
version:     0.1.0
synopsis:    A container backend toolkit

<<: *defaults

dependencies:
- base
- bytestring           ^>= 0.10
- conduit              ^>= 1.3.3
- conversions          ^>= 0.0.3
- cryptonite           >= 0.25 && <= 0.29
- exceptions           ^>= 0.10
- hashable             ^>= 1.3
- mprelude             ^>= 0.2
- mrio-log             ^>= 0.0.1
- mrio-core            ^>= 0.0.1
- mtl                  ^>= 2.2
- pathtype             ^>= 0.8
- resourcet            ^>= 1.2.4
- source-constraints   ^>= 0.0.1
- tar                  ^>= 0.5
- template-haskell
- text                 ^>= 1.2
- th-lift-instances    ^>= 0.1
- typed-process        ^>= 0.2
- unliftio             ^>= 0.2
- unliftio-core        ^>= 0.2
- unordered-containers ^>= 0.2
- uuid                 ^>= 1.3

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src
  exposed-modules:
  - CBT
  - CBT.Backend
  - CBT.Environment
  - CBT.IncrementalState
  - CBT.TH
  - CBT.Types

tests:
  test:
    <<: *test
    dependencies:
    - cbt
    - devtools
    - tasty
    - tasty-hunit
