_common/package: !include "../common/package.yaml"

name:        cbt
version:     0.2.5
synopsis:    A container backend toolkit

<<: *defaults

dependencies:
- base
- bytestring
- conduit              >= 1.3.3
- conversions
- crypton
- directory
- exceptions           >= 0.10
- filepath
- hashable             >= 1.3
- mprelude             >= 0.2
- mio-core
- mio-log
- mtl
- pathtype
- resourcet            >= 1.2.4
- source-constraints
- tar                  >= 0.5
- template-haskell
- text
- th-lift-instances    >= 0.1
- typed-process        >= 0.2
- unliftio             >= 0.2
- unliftio-core        >= 0.2
- unordered-containers >= 0.2
- uuid                 >= 1.3

library:
  source-dirs: src

tests:
  test:
    <<: *test
    dependencies:
    - cbt
    - devtools
    - tasty
    - tasty-hunit
