_common/package: !include "../common/package.yaml"

name:    pgt
version: 0.0.3

<<: *defaults

extra-source-files:
- examples/*.sql
- examples/*.sql.expected

dependencies:
- aeson
- attoparsec
- base
- bytestring
- containers           >= 0.6
- conversions          >= 0.0.3
- dbt
- directory            >= 1.3
- filepath             >= 1.4
- mprelude
- mtl
- nonempty-containers
- optparse-applicative >= 0.15
- ordered-containers   >= 0.2
- pathtype             >= 0.8.1
- scientific
- source-constraints
- tasty                >= 1.3.1
- tasty-mgolden        >= 0.0.1
- text
- typed-process        >= 0.2
- unix
- unliftio             >= 0.2
- vector

flags:
  development:
    <<: *development_flag
  build-executable:
    description: Build PGT executable
    default: false
    manual: true

executables:
  pgt:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - pgt
    when:
    - condition: flag(build-executable)
      then:
        buildable: true
      else:
        buildable: false

tests:
  test:
    <<: *test
    dependencies:
    - cbt
    - dbt
    - devtools
    - pgt
    - tasty-hunit
