name:    pgt
version: 0.0.1
github:  mbj/pgt
license: BSD3

extra-source-files:
- examples/*.sql
- examples/*.sql.expected

dependencies:
- base                      >= 4.13 && <5
- bytestring                ^>= 0.10
- containers                ^>= 0.6
- conversions               ^>= 0.0.3
- dbt-postgresql-connection ^>= 0.1.0
- directory                 ^>= 1.3
- filepath                  ^>= 1.4
- mprelude                  ^>= 0.2.0
- optparse-applicative      ^>= 0.15 || ^>= 0.16
- ordered-containers        ^>= 0.2
- pathtype                  ^>= 0.8.1
- source-constraints        ^>= 0.0.1
- tasty                     ^>= 1.3.1
- tasty-mgolden             ^>= 0.0.1
- text                      ^>= 1.2
- text-conversions          ^>= 0.3
- typed-process             ^>= 0.2
- unix                      ^>= 2.7
- unliftio                  ^>= 0.2

library:
  source-dirs: src

default-extensions:
- CPP
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin-opt=SourceConstraints:local:Pgt
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

executables:
  pgt:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - pgt

tests:
  test:
    main:          test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - cbt                      ^>= 0.1.0
    - dbt-postgresql-container ^>= 0.1.0
    - devtools ^>= 0.1.0
    - pgt
