_common/package: !include "../common/package.yaml"

name:               oauth
synopsis:           Haskell Oauth library
description:        Haskell Oauth library currently supporting only google auth
version:            0.0.2
github:             mbj/mhs/oauth
license:            BSD3
author:             gamsnjaga@gmail.com
maintainer:         gamsnjaga@gmail.com, epicallan.al@gmail.com, mbj@schirp-dso.com
category:           Oauth, Web
extra-source-files: README.md

<<: *defaults

dependencies:
- base
- aeson
- aeson-pretty
- base64-bytestring
- bounded
- bytestring
- conversions
- http-client
- http-mclient
- http-types
- exceptions
- mtl
- mrio-core
- mprelude
- network-uri
- nonce
- text
- time
- utf8-string

default-extensions:
- AllowAmbiguousTypes
- OverloadedStrings
- OverloadedLists
- DeriveFoldable
- DeriveFunctor
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DeriveTraversable
- DerivingVia
- DataKinds
- KindSignatures
- DuplicateRecordFields
- ConstraintKinds
- EmptyCase
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- MonoLocalBinds
- MultiWayIf
- MultiParamTypeClasses
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- ViewPatterns

tests:
  test:
    <<: *test
    dependencies:
    - devtools ^>= 0.1.0
