_common/package: !include "../common/package.yaml"

name:               oauth
synopsis:           Haskell Oauth library
description:        Haskell Oauth library, mostly datatypes.
version:            0.0.4
github:             mbj/mhs/oauth
license:            BSD3
author:             gamsnjaga@gmail.com
maintainer:         gamsnjaga@gmail.com, epicallan.al@gmail.com, mbj@schirp-dso.com
category:           Oauth, Web
extra-source-files: README.md

<<: *defaults

dependencies:
- aeson
- base
- base64-bytestring
- bounded
- bytestring
- conversions
- exceptions
- http-client
- http-mclient
- http-types
- mprelude
- mrio-core
- mtl
- random
- text

default-extensions:
- AllowAmbiguousTypes
- OverloadedStrings
- OverloadedLists
- DeriveFoldable
- DeriveFunctor
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DeriveTraversable
- DerivingVia
- DataKinds
- KindSignatures
- DuplicateRecordFields
- ConstraintKinds
- EmptyCase
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- MonoLocalBinds
- MultiWayIf
- MultiParamTypeClasses
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- ViewPatterns

tests:
  test:
    <<: *test
    dependencies:
    - devtools
