name:                oauth
synopsis:            Haskell Oauth library
description:         Haskell Oauth library currently supporting only google auth
version:             0.0.1
github:              mbj/mhs/oauth
license:             BSD3
author:              gamsnjaga@gmail.com
maintainer:          gamsnjaga@gmail.com, epicallan.al@gmail.com, mbj@schirp-dso.com
category:            Oauth, Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - AllowAmbiguousTypes
  - OverloadedStrings
  - OverloadedLists
  - DeriveFoldable
  - DeriveFunctor
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DeriveTraversable
  - DerivingVia
  - DataKinds
  - KindSignatures
  - DuplicateRecordFields
  - ConstraintKinds
  - EmptyCase
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoImplicitPrelude
  - MonoLocalBinds
  - MultiWayIf
  - MultiParamTypeClasses
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

flags:
  development:
    description: Run GHC with development flags
    default: false
    manual: true

when:
  - condition: flag(development)
    then:
      ghc-options:
      - -Werror
      - -fplugin=SourceConstraints
      dependencies:
      - source-constraints ^>= 0.0.2
    else:
      ghc-options: -Wwarn

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-pretty
    - base64-bytestring
    - bounded
    - bytestring
    - conversions
    - http-client
    - http-mclient
    - http-types
    - exceptions
    - mtl
    - mrio-core
    - mprelude
    - network-uri
    - nonce
    - text
    - time
    - utf8-string
tests:
  test:
    main: test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools ^>= 0.1.0
