_common/package: !include "../common/package.yaml"

name:        source-constraints
version:     0.0.2
synopsis:    Source constraints GHC plugin
category:    CodeQuality
description: |
  Please visit the README at <https://github.com/mbj/mhs/blob/main/source-constraints/README.md>
  for usage information.

<<: *defaults

dependencies:
- attoparsec >= 0.13
- base
- bytestring >= 0.10
- filepath   >= 1.4
- ghc        ^>= 9.2 || ^>= 9.4
- syb        >= 0.7
- text

extra-doc-files:
- README.md

extra-source-files:
- test/LocalModuleExplicitImport.hs
- test/UnsortedIE.hs
- test/UnsortedIEThingWith.hs
- test/UnsortedImportStatement.hs
- test/UnsortedMultipleDeriving.hs

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-local-signatures
- -Wmissing-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

when:
- condition: flag(development)
  then:
    ghc-options: -Werror
  else:
    ghc-options: -Wwarn

default-extensions:
- DerivingStrategies
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- Strict

library:
  source-dirs:
  - src
  exposed-modules:
  - SourceConstraints
  - SourceConstraints.LocalModule

tests:
  hspec:
    main:          Spec.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - ghc-paths
    - heredoc
    - hspec
    - source-constraints
