_common/package: !include "../common/package.yaml"

name:        xray
version:     0.0.2
synopsis:   Recording and submitting traces for Amazon XRay

<<: *defaults

dependencies:
- aeson
- attoparsec
- base
- binary
- bounded
- bytestring
- containers
- conversions
- http-types
- mprelude
- mrio-core
- mtl
- network ^>= 3.1 && >= 3.1.2
- pathtype
- random
- scientific
- source-constraints
- symbols
- template-haskell
- text
- time
- unliftio
- unordered-containers

library:
  source-dirs: src

tests:
  test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
    - tasty
    - tasty-hunit
    - xray
