_common/package: !include "../common/package.yaml"

name:               lambda-runtime
synopsis:           A runtime environment for Haskell applications running on AWS Lambda.
description:        A runtime environment for Haskell applications running on AWS Lambda.
version:            0.0.1
author:             epicallan.al@gmail.com, Markus Schirp, Makara digital
maintainer:         epicallan.al@gmail.com, mbj@schirp-dso.com
category:           Web,AWS
extra-source-files: README.md

<<: *defaults

dependencies:
- base
- aeson
- bytestring
- conversions
- http-client
- http-types
- exceptions
- mtl
- mprelude
- optparse-applicative >= 0.15
- text

flags:
  development:
    <<: *development_flag
  example:
    description: Build CLI example
    default: false
    manual: true

library:
  source-dirs: src

executables:
  cli-example:
    source-dirs: example
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - aeson
      - aeson-pretty
      - lambda-runtime
      - optparse-applicative
      - unordered-containers
    when:
    - condition: flag(example)
      then:
        buildable: true
      else:
        buildable: false

tests:
  test:
    <<: *test
