_common/package: !include "../common/package.yaml"

name:               lambda-alb
synopsis:           AWS lambda ALB integration
description:        AWS lambda ALB integration
version:            0.0.7
author:             epicallan.al@gmail.com, Markus Schirp, Makara digital
maintainer:         epicallan.al@gmail.com, mbj@schirp-dso.com
category:           Web,AWS
extra-source-files: README.md

<<: *defaults

dependencies:
- aeson             >= 2.0
- base
- base64-bytestring
- bytestring
- case-insensitive
- containers
- exceptions
- http-client
- http-types
- lambda-runtime
- mprelude
- text

executables:
  bootstrap:
    source-dirs: example
    main: Main.hs
    dependencies:
      - base
      - aeson
      - lambda-alb
      - lambda-runtime

tests:
  test:
    <<: *test
