_common/package: !include "../common/package.yaml"

name:        stack-deploy
version:     0.0.9
synopsis:    Utilities around cloudformation templates
license:     BSD3

<<: *defaults

dependencies:
- aeson                   >= 1.4
- aeson-pretty            >= 0.8
- amazonka                >= 2.0
- amazonka-cloudformation >= 2.0
- amazonka-core           >= 2.0
- amazonka-s3             >= 2.0
- attoparsec              >= 0.13
- base
- bounded
- bytestring
- cli-utils
- conduit                 >= 1.3
- containers              >= 0.6
- conversions
- exceptions              >= 0.10
- filepath                >= 1.4
- http-types              >= 0.12
- lens
- mio-amazonka
- mio-core
- mono-traversable
- mprelude
- mtl
- optparse-applicative    >= 0.14
- random                  >= 1.1
- source-constraints      >= 0.0.1
- stratosphere            >= 1.0
- stratosphere-ecs        >= 1.0
- stratosphere-iam        >= 1.0
- stratosphere-lambda     >= 1.0
- stratosphere-logs       >= 1.0
- stratosphere-s3         >= 1.0
- tasty                   >= 1.3
- tasty-mgolden           >= 0.0.1
- text
- time
- unliftio                >= 0.2
- vector                  >= 0.12

tests:
  test:
    <<: *test
