_common/package: !include "../common/package.yaml"

name:        stack-deploy
version:     0.0.2
synopsis:    Utilities around cloudformation templates
license:     BSD3

<<: *defaults

dependencies:
- aeson                   >= 1.4
- aeson-pretty            >= 0.8
- amazonka
- amazonka-cloudformation
- amazonka-core
- amazonka-s3
- attoparsec              >= 0.13
- base
- bytestring
- conduit                 >= 1.3
- containers              >= 0.6
- conversions
- exceptions              >= 0.10
- filepath                >= 1.4
- hashable                >= 1.2
- http-types              >= 0.12
- lens
- mprelude
- mrio-core
- mrio-amazonka
- mtl
- optparse-applicative    >= 0.14
- random                  >= 1.1
- source-constraints      >= 0.0.1
- stratosphere            >= 0.58
- tasty                   >= 1.3
- tasty-mgolden           >= 0.0.1
- text
- time
- unliftio                >= 0.2
- unordered-containers    >= 0.2
- vector                  >= 0.12

tests:
  test:
    <<: *test
