name: example

dependencies:
- base

flags:
  lht:
    description: Use LHT settings
    default: false
    manual: true

executables:
  hello-world:
    main: HelloWorld.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    when:
    - condition: flag(lht)
      ld-options: -static
      cc-options: -static
      ghc-options: -static
