_common/package: !include "../common/package.yaml"

name:        tasty-mgolden
version:     0.0.2
synopsis:    Golden testing provider for tasty with muti-line diff output
category:    Testing
tested-with: GHC ==8.6.5 || ==8.8.4 || ==8.10.2
description: |
  Please visit the README at <https://github.com/mbj/tasty-mgolden#readme>
  for usage information.

<<: *defaults

dependencies:
- ansi-terminal >= 0.9
- Diff          >= 0.3.4
- base
- filepath
- tasty         >= 1.3.1
- text

extra-doc-files: README.md

default-extensions:
- DerivingStrategies
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- StrictData

tests:
  hlint:
    main:          HLint.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hlint

  golden:
    main:          test/Test.hs
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - directory
    - tasty-expected-failure
    - tasty-hunit
    - tasty-mgolden
    - temporary
    - typed-process

executables:
  tasty-mgolden-example:
    main:          example/Test.hs
    other-modules: []
    default-extensions:
    - ImplicitPrelude
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-implicit-prelude
    dependencies:
    - tasty-expected-failure
    - tasty-hunit
    - tasty-mgolden
    when:
    - condition: flag(development)
      then:
        buildable: true
      else:
        buildable: false
